server:
  port: 8005  #端口号
eureka:
  client:
    service-url:
      defaultZone: http://47.93.30.178:6001/eureka/  #注册中心地址
spring:
  application:
    name: pwonline-orders-create-time-provider #本服务名字
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.17
    port: 6379
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: ppp
    password: ppp
     # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    name: orders
  profiles:
    active: dev

logging:
  level: debug
---
mybatis:
  mapperLocations: classpath:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  zipkin:
#    base-url: http://localhost:7700
#  sleuth:
#    sampler:
#      percentage: 1.0
